"""Aggiunta campo image

Revision ID: 42effcb836d8
Revises: 9a20fe1c263b
Create Date: 2023-01-03 15:25:37.253894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42effcb836d8'
down_revision = '9a20fe1c263b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
